import os
from pathlib import Path

REPOSITORY_PATH = Path.home() / ".seki"
DRONE_PATH = REPOSITORY_PATH / ".drone.yml"
DRONE_SERVER = os.environ["DRONE_SERVER"]
DRONE_TOKEN = os.environ["DRONE_TOKEN"]
SEKI_PROJECT_OWNER = os.environ["SEKI_PROJECT_OWNER"]
SEKI_PROJECT_REPO = os.environ["SEKI_PROJECT_REPO"]
DRONE_PROJECT = f"{DRONE_SERVER}/{SEKI_PROJECT_OWNER}/{SEKI_PROJECT_REPO}"
